Repository josev814/csc470_ntss, pull requests merged in 2023-11, with the labels that each got.

#20 excluding envvars in the build directory
  Build/.gitignore
Labels: documentation, dependencies

#21 updating envvars to include MYSQL_PWD variable
  Build/appenvvars.example
  Build/dbenvvars.example
Labels: documentation, dependencies

#22 updating compose down to include remove orphans
  Readme.md
Labels: documentation

#14 Josev814/favicon
  app/public_html/static/images/favicon/android-chrome-192x192.png
  app/public_html/static/images/favicon/android-chrome-512x512.png
  app/public_html/static/images/favicon/apple-touch-icon.png
  app/public_html/static/images/favicon/favicon-16x16.png
  app/public_html/static/images/favicon/favicon-32x32.png
  app/public_html/static/images/favicon/favicon.ico
  app/public_html/static/images/favicon/site.webmanifest
  ntss_www/ntss/templates/blocks/admin_header.html
  ntss_www/ntss/templates/blocks/header.html
Labels: enhancement

#23 updating favicon locations
  Build/nginx/sites-available/default
  ntss_www/static/images/favicon/android-chrome-192x192.png
  ntss_www/static/images/favicon/android-chrome-512x512.png
  ntss_www/static/images/favicon/apple-touch-icon.png
  ntss_www/static/images/favicon/favicon-16x16.png
  ntss_www/static/images/favicon/favicon-32x32.png
  ntss_www/static/images/favicon/favicon.ico
  ntss_www/static/images/favicon/site.webmanifest
Labels: enhancement

#24 Making login work using sessions and cookies
  .github/workflows/code-coverage.yml
  .github/workflows/pylint.yml
  Build/database_setup/setup.sql
  Build/docker-compose.yml
  Build/dockerfile
  Build/gunicorn/gunicorn.conf.py
  Build/supervisor.conf
  ntss_www/ntss/config/constants.py
  ntss_www/ntss/controllers/controller.py
  ntss_www/ntss/controllers/ntss.py
  ntss_www/ntss/controllers/routes.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/models/database.py
  ntss_www/ntss/models/session.py
  ntss_www/ntss/models/user.py
  ntss_www/ntss/templates/403.html
  ntss_www/ntss/templates/blocks/admin_top.html
  ntss_www/ntss/templates/blocks/error_modal.html
  ntss_www/ntss/templates/blocks/nav/exhibitor.html
  ntss_www/ntss/templates/events_list.html
  ntss_www/ntss/templates/forgot_password.html
  ntss_www/ntss/templates/login.html
  ntss_www/ntss/views/events.py
  ntss_www/ntss/views/ntss.py
  ntss_www/ntss/views/routes.py
  ntss_www/ntss/views/users.py
  ntss_www/ntss/views/views.py
  ntss_www/static/images/favicon/site.webmanifest
  ntss_www/wsgi.py
  requirements.txt
  tests/test_sessions.py
Labels: enhancement, dependencies

#29 Navigation Bug Fix
  ntss_www/ntss/templates/blocks/navigation.html
Labels: bug

#30 Jvargas/wiring up list users
  ntss_www/ntss/controllers/ntss.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/models/database.py
  ntss_www/ntss/models/user.py
  ntss_www/ntss/templates/blocks/nav/observer.html
  ntss_www/ntss/templates/blocks/navigation.html
  ntss_www/ntss/templates/dashboard.html
  ntss_www/ntss/templates/events_list.html
  ntss_www/ntss/templates/list_users.html
  ntss_www/ntss/views/ntss.py
  ntss_www/ntss/views/users.py
  tester
Labels: enhancement, dependencies

#26 Adding Create_User as functionality
  Build/database_setup/setup.sql
  ntss_www/ntss/controllers/ntss.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/models/database.py
  ntss_www/ntss/models/user.py
  ntss_www/ntss/templates/add_user.html
  ntss_www/ntss/templates/blocks/error_modal.html
  ntss_www/ntss/templates/blocks/nav/ntss_admin.html
  ntss_www/ntss/templates/blocks/nav/observer.html
  ntss_www/ntss/templates/blocks/navigation.html
  ntss_www/ntss/templates/dashboard.html
  ntss_www/ntss/templates/events_list.html
  ntss_www/ntss/templates/list_users.html
  ntss_www/ntss/views/ntss.py
  ntss_www/ntss/views/users.py
  ntss_www/ntss/views/views.py
  ntss_www/wsgi.py
Labels: enhancement

#31 adding my profile
  ntss_www/ntss/controllers/controller.py
  ntss_www/ntss/controllers/ntss.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/models/database.py
  ntss_www/ntss/models/user.py
  ntss_www/ntss/templates/blocks/admin_top.html
  ntss_www/ntss/templates/dashboard.html
  ntss_www/ntss/templates/user_profile.html
  ntss_www/ntss/views/ntss.py
  ntss_www/ntss/views/users.py
  ntss_www/ntss/views/views.py
  ntss_www/wsgi.py
Labels: enhancement

#36 updating code coverage to use docker
  .github/workflows/code-coverage.yml
  Build/docker-compose.yml
  tests/test_main.py
  tests/test_sessions.py
Labels: enhancement

#35 Edit/Delete user functionality
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/models/database.py
  ntss_www/ntss/models/user.py
  ntss_www/ntss/templates/blocks/error_modal.html
  ntss_www/ntss/templates/users/add_user.html
  ntss_www/ntss/templates/users/edit_user.html
  ntss_www/ntss/templates/users/list_users.html
  ntss_www/ntss/templates/users/user_profile.html
  ntss_www/ntss/views/users.py
  ntss_www/wsgi.py
Labels: enhancement

#34 Ryan/state_fix
  Build/database_setup/setup.sql
Labels: bug

#37 adding tables for events and venues
  .github/workflows/pylint.yml
  Build/database_setup/setup.sql
  ntss_www/ntss/controllers/events.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/controllers/venues.py
  ntss_www/ntss/models/database.py
  ntss_www/ntss/models/event.py
  ntss_www/ntss/models/user.py
  ntss_www/ntss/models/venue.py
  ntss_www/ntss/templates/blocks/nav/exhibitor.html
  ntss_www/ntss/templates/blocks/nav/ntss_admin.html
  ntss_www/ntss/templates/blocks/nav/observer.html
  ntss_www/ntss/templates/events/add_edit.html
  ntss_www/ntss/templates/events/event_info.html
  ntss_www/ntss/templates/events/events_list.html
  ntss_www/ntss/templates/events/no_items.html
  ntss_www/ntss/templates/events/not_found.html
  ntss_www/ntss/templates/events/view.html
  ntss_www/ntss/templates/events_list.html
  ntss_www/ntss/templates/venues/add_edit.html
  ntss_www/ntss/templates/venues/list.html
  ntss_www/ntss/templates/venues/no_items.html
  ntss_www/ntss/templates/venues/not_found.html
  ntss_www/ntss/templates/venues/view.html
  ntss_www/ntss/views/events.py
  ntss_www/ntss/views/venues.py
  ntss_www/wsgi.py
Labels: enhancement

#39 Forgot Password Implemented
  ntss_www/ntss/controllers/ntss.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/models/user.py
  ntss_www/ntss/templates/forgot_password.html
  ntss_www/ntss/templates/login.html
  ntss_www/ntss/templates/ntss/register.html
  ntss_www/ntss/views/ntss.py
  ntss_www/ntss/views/users.py
  ntss_www/static/css/signin.css
  ntss_www/wsgi.py
Labels: enhancement

#44 Caileb/Add_Slogan_To_Event
  Build/database_setup/setup.sql
  ntss_www/ntss/controllers/events.py
  ntss_www/ntss/models/event.py
  ntss_www/ntss/templates/events/add_edit.html
  ntss_www/ntss/templates/events/add_edit_event.html
  ntss_www/ntss/templates/events/no_items.html
  ntss_www/ntss/templates/events/view.html
  ntss_www/ntss/views/events.py
Labels: enhancement

#45 Tyuss/ntss header (dashboard)
  ntss_www/ntss/templates/blocks/admin_top.html
  ntss_www/ntss/templates/dashboard.html
Labels: bug, enhancement

#48 requiring start and end dates
  ntss_www/ntss/templates/events/add_edit.html
  ntss_www/ntss/templates/events/add_edit_event.html
Labels: bug

#41 adding cost to the venues
  Build/database_setup/setup.sql
  ntss_www/ntss/models/venue.py
  ntss_www/ntss/templates/events/view.html
  ntss_www/ntss/templates/venues/add_edit.html
  ntss_www/ntss/templates/venues/view.html
Labels: enhancement

#32 Ryan/my profile
  ntss_www/ntss/templates/user_profile.html
Labels: enhancement

#46 adjusting the event to use a date instead of datetime
  Build/database_setup/setup.sql
  ntss_www/ntss/templates/events/add_edit.html
  ntss_www/ntss/templates/events/add_edit_event.html
  ntss_www/ntss/templates/events/view.html
Labels: enhancement

#51 Route Correction For Event Staff
  ntss_www/ntss/controllers/events.py
  ntss_www/ntss/templates/blocks/nav/event_staff.html
  ntss_www/ntss/templates/events/no_items.html
  ntss_www/ntss/views/events.py
  ntss_www/wsgi.py
Labels: correction

#50 Jose/add user to event
  Build/database_setup/setup.sql
  Project.md
  ntss_www/ntss/config/constants.py
  ntss_www/ntss/controllers/controller.py
  ntss_www/ntss/controllers/events.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/controllers/venues.py
  ntss_www/ntss/models/database.py
  ntss_www/ntss/models/event.py
  ntss_www/ntss/models/transactions.py
  ntss_www/ntss/templates/blocks/payment.html
  ntss_www/ntss/templates/events/add_attendee.html
  ntss_www/ntss/templates/events/view.html
  ntss_www/ntss/views/events.py
  ntss_www/ntss/views/views.py
  ntss_www/static/css/admin.css
  ntss_www/wsgi.py
  tests/test_main.py
Labels: enhancement

#58 adding phpmyadmin image
  Build/docker-compose.yml
Labels: enhancement

#59 fixing the payment type not inserting into the db
  ntss_www/ntss/models/transactions.py
Labels: bug

#62 fixing required fields on add_edit event
  ntss_www/ntss/templates/events/add_edit_event.html
Labels: bug

#63 Jose/fix required venue fee
  ntss_www/ntss/templates/events/add_edit.html
Labels: bug

#64 Ryan/report for number of participants
  ntss_www/ntss/controllers/events.py
  ntss_www/ntss/models/event.py
  ntss_www/ntss/templates/events/get_report.html
  ntss_www/ntss/templates/events/view.html
  ntss_www/ntss/views/events.py
  ntss_www/ntss/views/revenue.py
  ntss_www/wsgi.py
Labels: enhancement

#65 Jvargas/booth registration
  .github/workflows/pylint.yml
  ntss_www/ntss/controllers/events.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/models/database.py
  ntss_www/ntss/models/event.py
  ntss_www/ntss/models/transactions.py
  ntss_www/ntss/models/user.py
  ntss_www/ntss/templates/access_denied.html
  ntss_www/ntss/templates/blocks/admin_header.html
  ntss_www/ntss/templates/blocks/header.html
  ntss_www/ntss/templates/blocks/nav/event_staff.html
  ntss_www/ntss/templates/blocks/nav/exhibitor.html
  ntss_www/ntss/templates/blocks/nav/ntss_admin.html
  ntss_www/ntss/templates/blocks/payment.html
  ntss_www/ntss/templates/events/add_attendee.html
  ntss_www/ntss/templates/events/events_list.html
  ntss_www/ntss/templates/events/exhibits/edit.html
  ntss_www/ntss/templates/events/exhibits/exhibitors_list.html
  ntss_www/ntss/templates/events/exhibits/list.html
  ntss_www/ntss/templates/events/exhibits/view_exhibit.html
  ntss_www/ntss/templates/events/no_items.html
  ntss_www/ntss/templates/events/view.html
  ntss_www/ntss/templates/no_items.html
  ntss_www/ntss/views/events.py
  ntss_www/ntss/views/users.py
  ntss_www/static/css/admin.css
  ntss_www/static/css/bootstrap.min.css
  ntss_www/static/css/fonts.googleapis.com.css2.css
  ntss_www/static/fonts/kJF1BvYX7BgnkSrUwT8OhrdQw4oELdPIeeII9v6oDMzByHX9rA6RzaxHMPdY43zj-jCxv3fzvRNU22ZXGJpEpjC_1v-p_4MrImHCIJIZrDCvHOej.woff2
  ntss_www/static/js/bootstrap.bundle.min.js
  ntss_www/wsgi.py
Labels: enhancement

#66 denying access to observer
  ntss_www/ntss/controllers/ntss.py
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/templates/login.html
  ntss_www/ntss/templates/ntss/register.html
  ntss_www/ntss/views/users.py
Labels: bug, enhancement

#70 fixing list page missing session data
  ntss_www/ntss/controllers/users.py
  ntss_www/ntss/templates/users/user_profile.html
  ntss_www/ntss/views/users.py
Labels: bug

#69 Jose/fix event reports
  ntss_www/ntss/templates/blocks/payment.html
  ntss_www/ntss/templates/events/view.html
Labels: bug

#68 fixing issues with exhibits navigation
  ntss_www/ntss/templates/blocks/nav/ntss_admin.html
  ntss_www/ntss/templates/no_items.html
  ntss_www/ntss/views/events.py
Labels: bug

#67 adjusting our default event to be in our date range for the presentation
  Build/database_setup/setup.sql
Labels: correction

#73 fixing exhibitors list when no exhibits are found
  ntss_www/ntss/templates/events/exhibits/exhibitors_list.html
Labels: bug

#71 fixing revenue bug
  ntss_www/ntss/controllers/revenue.py
  ntss_www/ntss/templates/revenue_report.html
Labels: bug

#74 Dashboard design:
  ntss_www/ntss/templates/blocks/nav/event_staff.html
  ntss_www/ntss/templates/blocks/nav/exhibitor.html
  ntss_www/ntss/templates/dashboard.html
  ntss_www/static/images/logo-png.png
Labels: bug, enhancement

#75 fixing login issue
  ntss_www/ntss/controllers/users.py
Labels: bug
